name: Render and Deploy Site

on:
  schedule:
    - cron: '12 12 * * 1'
  push:
    branches: main
  workflow_dispatch:

jobs:
  render:
    if: startsWith(github.repository, 'rfordatascience/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up DESCRIPTION dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
