# This GitHub Action checks incoming TidyTuesday dataset submissions.
# It verifies that all required files are present, images meet size and 
# dimension constraints, and provided URLs are accessible. Coded with the help 
# of Google Gemini.

name: PR Submission Check

on:
  pull_request_target:
    paths:
      - 'data/curated/**'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to check'
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  
jobs:
  check-submission:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Determine PR Number
        id: pr_num
        run: |
          # Use the PR number from the event trigger if available,
          # otherwise use the manually entered number.
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
          else
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      # For pull_request events, the action automatically checks out the PR's merge commit.
      # For workflow_dispatch, we explicitly check out the PR branch head.
      - name: Checkout PR Code
        uses: actions/checkout@v5
        # with:
        #   ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/pull/{0}/head', github.event.inputs.pr_number) || '' }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages("pak")
          pak::pak(c("yaml", "fs", "magick", "purrr", "stringr", "glue", "httr", "cli"))
        shell: Rscript {0}

      - name: Run Submission Checks
        id: run_checks
        run: Rscript .github/scripts/check_curated.R

      - name: Comment on PR
        uses: actions/github-script@v8
        env:
          PR_NUMBER: 
        with:
          script: |
            const fs = require('fs');
            const commentBody = fs.readFileSync('pr_comment.md', 'utf8');
          
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
              body: commentBody
            });

      - name: Fail workflow if checks failed
        if: steps.run_checks.outputs.check_status == 'failure'
        run: exit 1
