# This GitHub Action checks incoming TidyTuesday dataset submissions.
# It verifies that all required files are present, images meet size and 
# dimension constraints, and provided URLs are accessible. Coded with the help 
# of Google Gemini.

name: PR Submission Check

on:
  pull_request_target:
    paths:
      - 'data/curated/**'

# Use the principle of least privilege. We only need to read contents.
permissions:
  contents: read
  pull-requests: write
  
jobs:
  check-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR Number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      # For pull_request events, the action automatically checks out the PR's merge commit.
      - name: Checkout PR Code
        uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ env.PR_NUMBER }}/head

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages("pak")
          pak::pak(c(
            "cli",
            "fs",
            "glue",
            "httr",
            "knitr",
            "magick",
            "purrr",
            "stringr",
            "yaml"
          ))
        shell: Rscript {0}

      - name: Run Submission Checks
        id: run_checks
        run: Rscript .github/scripts/check_curated.R

      - name: Comment on PR
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
        with:
          script: |
            const fs = require('fs');
            const commentBody = fs.readFileSync('pr_comment.md', 'utf8');
          
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
              body: commentBody
            });

      - name: Fail workflow if checks failed
        if: steps.run_checks.outputs.check_status == 'failure'
        run: exit 1
